### ISSUE TITLE
Make better wording for error box

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#211]
Currently it's just "We're having some trouble. Maybe try switching to a better network connection?", which I half-assed. If we could figure out better words to explain what is going on and what the user should do, that would be good. (For reference, this box is displayed on connectivity failure and on audioLag.)

**Comment by gwillen** [comment]
"""
The app is having some trouble. This can be due to network issues, or load on your computer. If you aren't hearing smooth sound, we suggest trying some of the following, and then refreshing the page if necessary:
- Close any other apps or browser tabs that you're not using
- Disable browser extensions (or switch to incognito mode)
- Use a wired network connection, or move to somewhere with stronger wifi
- Stop any downloads or backups that are running
"""

How's that? Too much text?

**Comment by taymonbeal** [comment]
I don't really have an opinion on whether it's too much text, sorry.

"If you aren't hearing smooth sound"--note that this warning can be displayed during non-BB slides (because without a network connection you can't get stuff like slide advancements). Is there a way we could sensibly reword in light of this? If not I could see just using it as-is.

**Comment by gwillen** [comment]
I was only asking about too much text insofar as I have no idea where we're displaying this or how we're styling it. So I wasn't sure how much room we have.

... also how _are_ we styling this? When I run locally I get a red box in the top-left corner overlapping the slide controls. (Ohhh, but only lead will have those, so maybe that's a good place for non-lead people, and lead people should suck it up and get better connections so they don't see this?)

Here's a small change that maybe helps -- I'm assuming that the main symptom people will get if rE disconnects and can't reconnect on a non-BB slide will be "slide doesn't advance when it should", in which case "app seems stuck" is the best I can do in a few words. There are times when the app will seem to be stuck but isn't (e.g. it takes 5-10 seconds to start and end BB songs), but I think that's ok because this dialog will only display if there is ALSO something actually going wrong.

"""
The app is having some trouble. This can be due to network issues, or load on your computer. If your sound is choppy, or if the app seems to be stuck, we suggest trying some of the following (and then refreshing the page if necessary):

Close any other apps or browser tabs that you're not using
Disable browser extensions (or switch to incognito mode)
Use a wired network connection, or move to somewhere with stronger wifi
Stop any downloads or backups that are running
"""

**Comment by taymonbeal** [comment]
I created #213 to invite Daniel to restyle the error box, since when I tried to make it according to Ray's spec it came out kind of ugly (because I'm not that good at this). If you feel qualified to take over #213 from Daniel I'm sure he'd appreciate it.

The slide controls are on top of the box, or at least they should be. If they're not that's a bug that I need to fix.

This is good wording for now; we could maybe change it as part of the restyling if need be. I'll make a PR for it.
