### ISSUE TITLE
Clarify distinction between last-bucket and no-bucket

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#233]
We should make sure to communicate to people that they'll be in the recording if they're in any bucket, including the last bucket, but not if they're in no bucket. We should also make sure that people are assigned to whichever one of those is appropriate.

(Are there any circumstances where we force anyone other than the leader into the last bucket, as opposed to no bucket? And do we want people without headphones, or with Bluetooth headphones, in the last bucket or in no bucket?)

**Comment by gwillen** [comment]
People who don't calibrate will show as being in the last bucket on their own screen, and they will hear the "last bucket" position, but they are effectively in "no bucket" because they are permanently muted.

Whether people without headphones end up there is entirely down to whether they calibrate, or follow the instructions and click "don't let anybody hear me." So I think it's pretty reasonable right now -- nobody will hear you if you click "don't let anybody hear me", otherwise you're in whatever bucket you're in.
