### ISSUE TITLE
Figure out admin panel

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#45]
Are we still going to build one? What will it do?

**Comment by Raemon** [comment]
context/thinking:

Jeff is building an admin panel for bucket brigade that manages audio. Upon reflection I'm not sure this was the right division of labor, because I think we'd ideally also have a ritual-engine version with some additional tools. 

The tools we'd ideally have are:
1. Remove people from Twilio
2. Block people from chatting
3. Move people to the end of the bucket chain
4. ip ban people, if they turn out to be deeply bad in some way.

It might be that we should encode these features directly into the ritualEngine frontend. i.e. make it so admins can right click on a twilio-thingy to remove someone from twilio, right click on someone in the chat to remove them from chat, etc.

(None of this needs to be done by the stress test, and I'd want to take stock after the stress test to see how smooth everything felt and how much it's worth investing in "hedge against terrible people ruining solution" vs "make sure solstice is generally good.)

**Comment by taymonbeal** [comment]
The baseline architecture that we'd want here would be a page that updates itself in real time through long polling, and that shows a list of everyone who's connected. Once we had that baseline, I could then tweak it to include the specific functionality we needed.

@dspeyer, do you think you will have time to do this (in addition to all the other stuff that needs to get done that requires your involvement) within the next couple days?

**Comment by Raemon** [comment]
I'm not sure the right abstraction is a separate panel. I think if I want
to mute somebody, it's because their Twilio image is abusive, or their
chats are abusive, or their bucket brigade is fucked up.

Bucketbrigade I think can be handled by the BB panel that already exists.

For the other two, I think I probably just want to be able to right-click
on a twilio avatar or chat-name, and have the ability to turn them into
spectator mode right then-and-there. (this _does_ require figuring out
special permissions for admin users on the main page. Maybe via magic link?)

**Comment by taymonbeal** [comment]
We figured out a way we can just do the thing inline.
