### ISSUE TITLE
Mirror people's self-video

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#62]

**Comment by Raemon** [comment]
What does this mean?

**Comment by taymonbeal** [comment]
If your webcam is on, one of the video feeds is of you from your local camera. @gwillen said that we should flip this horizontally so that it better matches what people expect.

**Comment by Raemon** [comment]
Ah, gotcha. Yeah upon reflection the mirror-image had been kinda annoying.

That said this is probably among the nice-to-have-iest-things.

**Comment by gwillen** [comment]
FWIW, maybe I just have an unusually asymmetrical face (or you both have unusually symmetrical ones) but it is very uncanny-valley and unpleasant for me to see my face live the right way around instead of mirrored.

(The first time I took a full-frame self-portrait photo and really looked at it, I honestly thought there was something wrong with the camera.)

**Comment by Raemon** [comment]
Nod. I think it'll be awhile before we get to this, but, like, you are
welcome to submit a PR at any time. :)

**Comment by dspeyer** [comment]
Done
