### ISSUE TITLE
ritualEngine keeps being weirdly sluggish (waiting for dead sessions?)

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#63]
@gwillen, @Raemon, and I kept seeing `6/9 ready=true` repeatedly in the debugging info.

**Comment by dspeyer** [comment]
6/9 ready=true means that the server knows of 9 clients, only 6 of which
have initialized, but it's ready to go ahead anyway because the first one
reported ready sufficiently long ago that we're happy going ahead without
the others.  That go-ahead logic probably needs tweaking, but if it's
saying ready=true, that's probably not related to whatever sluggishness
you're experiencing

>

**Comment by gwillen** [comment]
To be clear, "sluggish" in this case was: it reported "6/9 ready=true" repeatedly for several minutes but never started the song. (Bucket brigade was running but the backing track and the youtube video didn't start.)

**Comment by taymonbeal** [comment]
I think this got fixed when the bucket assignment system was rejiggered.
